### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by DexterMorg4n** [Cellules/cordova-audiofrequency#1]
On Cordova 3.6.4 it will generate an error because of the array declaration
Including **JLargeArrays-1.2.jar** from 
https://sites.google.com/site/piotrwendykier/software/jtransforms
will fix that issue

**Comment by moust** [comment]
Thanks for your feedback.
I had no error related to this when I made my tests on Android but I will check it on my future tests and add this dependency if necessary.

**Comment by moust** [comment]
Ok, I saw the error. It was a warning message in the console and the programme worked anyway, which is why I did not saw it.

I added the dependency in the plugin.xml file. Thanks for your help.
